// CSE30 assignment template
// 
// id: 
//
////////////////////////////////////////
#include "Version.h"

#ifndef MYNODELOOKUP_S
    .section .note.GNU-stack,"",%progbits
    .end
#else

    // version 1.0 08/22/2024
    .arch   armv6
    .arm
    .fpu    vfp
    .syntax unified

    #include "node.h"

    .extern strcmp
    .text

    .type   node_lookup, %function
    .global node_lookup
    // determine how many registers to save and set FP_OFF
    //.equ    FP_OFF, ??

    // preserved register use table fill this in to help you
    //
    // r4
    // r5
    // r6
    // r7
    // r8
    // r9

node_lookup:
    push    {r4-r7, fp, lr}
    add     fp, sp, #12
    mov     r4, r0
    mov     r5, r1

loop:
    cmp r4, #0
    beq not_found
    ldr r0, [r4, #4]
    mov r1, r5
    bl strcmp
    cmp r0, #0
    beq found
    ldr r4, [r4]
    b loop

found:
    mov r0, r4
    b end
not_found:
    mov r0, #0
end:
    sub sp, fp, #12
    pop {r4-r7, fp, lr}
    bx      lr                  // function return
    .size   node_lookup, (. - node_lookup)
    .section .note.GNU-stack,"",%progbits
.end
#endif
